Fix race condition in which client starts before server is ready.

diff --git a/bin/submit_iperf b/bin/submit_iperf
--- a/bin/submit_iperf
+++ b/bin/submit_iperf
@@ -24,6 +24,8 @@ parser.add_option("--report-from",help="Generate a report from iperf output.")
 (options,args) = parser.parse_args()
 
 if options.report_from:
+      # This option is called internally at the end of the test
+      # to extract data and generate a report.
       report = IperfReport(options.report_from)
       print report.toPrettyJSON()
       sys.exit(0)
@@ -34,7 +36,8 @@ if not iperf_path:
 
 basedir = options.base_submit_dir
 
-# create a new test directory
+# create a new test directory so different tests
+# do not stomp on each other
 i = 1
 while 1:
       testdir = os.path.join(basedir,"iperf_test_" + str(i))
@@ -43,7 +46,12 @@ while 1:
 
 dagdir = os.path.join(testdir,"dag")
 print "Using directory " + testdir
-os.makedirs(dagdir)
+
+# This will fail if there is a race and something else created
+# the test directory before we do.  Better to fail than to go
+# ahead and use the same directory as a different test instance.
+os.mkdir(testdir)
+os.mkdir(dagdir)
 
 #
 # The DAG that runs the test
@@ -53,8 +61,14 @@ F = file(dagfile,"w")
 F.write("""
 
   JOB iperf_server dag/iperf_server.sub
+
+  JOB iperf_server_wait dag/iperf_server_wait.sub
+  ABORT-DAG-ON iperf_server_wait 1
+
   JOB iperf_client dag/iperf_client.sub
   SCRIPT POST iperf_client dag/iperf_server_stop $RETURN
+  PARENT iperf_server_wait CHILD iperf_client
+
   JOB iperf_report dag/iperf_report.sub
   PARENT iperf_client CHILD iperf_report
 
@@ -68,7 +82,7 @@ F.write("""
        "port": options.port})
 
 #
-# The conor job that runs the iperf server
+# The condor job that runs the iperf server
 #
 server_subfile = os.path.join(dagdir,"iperf_server.sub")
 F = file(server_subfile,"w")
@@ -91,6 +105,24 @@ F.write("""
 
 """ % {"iperf_path": iperf_path,
        "port": options.port})
+
+#
+# The condor job that runs the iperf server
+#
+server_wait_subfile = os.path.join(dagdir,"iperf_server_wait.sub")
+F = file(server_wait_subfile,"w")
+F.write("""
+
+  universe = local
+  executable = dag/iperf_server_wait
+  arguments = dag/iperf_server.ulog
+  output = iperf_server_wait.out
+  error = iperf_server_wait.err
+  log = dag/iperf_server_wait.ulog
+  notification = never
+  queue
+
+""")
 
 #
 # The condor job that runs the iperf client
@@ -130,6 +162,44 @@ F.write("""
 """)
 
 #
+# The script that waits for the iperf server to start.
+#
+server_wait = os.path.join(dagdir,"iperf_server_wait")
+F = open(server_wait,"w")
+os.chmod(server_wait,0o755)
+F.write("""#!/bin/sh
+
+  die() {
+    echo $1 1>&2
+    exit 1
+  }
+
+  exec >& iperf_server_wait.out
+
+  SERVER_ULOG=$1
+  [ -f $SERVER_ULOG ] || die "$SERVER_ULOG does not exist in $(pwd)."
+
+  JOBID=$(awk '/^000 / {pos=match($2,/[0-9]+\.[0-9]+/); print substr($2,RSTART,RLENGTH)}' $SERVER_ULOG)
+
+  [ "$JOBID" != "" ] || die "Failed to find job id in iperf_server.ulog."
+
+  # while the server job is idle, wait
+  while [ 1 ]; do
+   status="$(condor_q $JOBID -format '%s\n' JobStatus)"
+   if [ "$status" = 1 ]; then   # idle
+     sleep 2
+   elif [ "$status" = 2 ]; then # running
+     break
+   else                         # held? removed?
+     die "Unexpected server job status $status"
+   fi
+  done
+
+  exit 0
+
+""")
+
+#
 # The script that stops the iperf server.
 # The simple thing to do would be to use condor_rm to stop it,
 # but that causes the DAG to be considered a failure, so
@@ -150,7 +220,7 @@ F.write("""#!/bin/sh
   exec >& iperf_server_stop.out
 
   SERVER_ULOG=dag/iperf_server.ulog
-  [ -f $SERVER_ULOG ] || die "iperf_server.ulog does not exist."
+  [ -f $SERVER_ULOG ] || die "$SERVER_ULOG does not exist in $(pwd)."
 
   JOBID=$(awk '/^000 / {pos=match($2,/[0-9]+\.[0-9]+/); print substr($2,RSTART,RLENGTH)}' $SERVER_ULOG)
 
@@ -162,6 +232,7 @@ F.write("""#!/bin/sh
 
 """)
 
+# submit the DAG to condor
 os.chdir(testdir)
 rc = os.system("condor_submit_dag dag/iperf.dag")
 if rc != 0:
